/**
 * Generates the product seed migration from the existing `src/data/site.js`
 * catalogue, so the database copy can never drift from the source data.
 *
 * Usage:  node supabase/generate-seed.mjs
 * Output: supabase/migrations/20261004000002_seed_products.sql
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PRODUCTS } from "../src/data/site.js";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "migrations", "20261004000002_seed_products.sql");

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? "null" : Number(v).toFixed(2));
const arr = (v) => (Array.isArray(v) && v.length ? `array[${v.map(q).join(",")}]` : "'{}'");
const js = (v) =>
  v === null || v === undefined ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const rows = PRODUCTS.map((p, i) => {
  const sizes = Array.isArray(p.sizes) && p.sizes.length ? p.sizes : ["Regular"];
  // The original frontend charged a flat ₱15 Large surcharge on every drink.
  const adjustments = Object.fromEntries(sizes.map((s) => [s, s === "Large" ? 15 : 0]));
  return `(
  ${q(p.id)},
  ${q(p.name)},
  ${q(p.description)},
  ${q(p.longDescription)},
  ${n(p.price)},
  ${p.compareAt ? n(p.compareAt) : "null"},
  ${q(p.category)},
  ${arr(p.tags)},
  ${q(p.image)},
  ${q(p.detailImage)},
  ${n(p.rating ?? 0)},
  ${Number(p.reviews ?? 0)},
  ${arr(sizes)},
  '${JSON.stringify(adjustments)}'::jsonb,
  ${q(p.ingredients)},
  ${js(p.nutrition)},
  ${p.inStock !== false},
  ${i + 1}
)`;
});

const sql = `-- =============================================================================
-- Kapresco — product catalogue seed (17 products) + promo codes
-- =============================================================================
-- Generated by supabase/generate-seed.mjs from src/data/site.js.
-- Do not edit by hand: re-run the generator instead.
--
-- Idempotent: product ids are the primary key and existing rows are never
-- duplicated or overwritten (ON CONFLICT DO NOTHING).
-- =============================================================================

insert into public.products (
  id, name, description, long_description, price, compare_at, category, tags,
  image, detail_image, rating, reviews_count, sizes, size_adjustments,
  ingredients, nutrition, in_stock, sort_order
)
values
${rows.join(",\n")}
on conflict (id) do nothing;

-- Promo codes previously hard-coded in the cart UI.
insert into public.promo_codes (code, type, value, free_shipping, label)
values
  ('KAPRESCO10', 'percent', 0.10, false, '10% off'),
  ('TARAKAT',    'amount',  25.00, true,  '₱25 off')
on conflict (code) do nothing;

-- Make sure every drink carries a size pricing table even if it was inserted
-- before this migration.
update public.products
   set size_adjustments = case
     when 'Large' = any(sizes) then '{"Regular":0,"Large":15}'::jsonb
     else '{"Regular":0}'::jsonb
   end
 where size_adjustments is null
    or size_adjustments = '{}'::jsonb;

select count(*) as products_seeded from public.products;
select count(*) as promo_codes_seeded from public.promo_codes;
`;

writeFileSync(out, sql, "utf8");
console.log(`Wrote ${out} (${PRODUCTS.length} products).`);
