import { getSupabase } from "../lib/supabase.js";

/**
 * Order service.
 *
 *  * The checkout draft (contact/address/totals shown between routes) stays in
 *    `sessionStorage` — it is transient UI state, not an order.
 *  * Real orders live in `orders` + `order_items`, scoped to the signed-in user.
 *  * `placeOrder()` calls the `place_order` PL/pgSQL function, which recomputes
 *    every price from `products`, writes the order, snapshots the line items
 *    and empties the cart in a single transaction. The client never decides
 *    what an order costs.
 */

const DRAFT_KEY = "kapresco.orderDraft";
const ORDER_SELECT = "*, order_items(*)";

function read() {
  try {
    const raw = window.sessionStorage.getItem(DRAFT_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function write(draft) {
  try {
    window.sessionStorage.setItem(DRAFT_KEY, JSON.stringify(draft));
  } catch {
    /* storage blocked — the flow still works for this page view */
  }
}

export function rowToOrder(row) {
  if (!row) return null;
  const items = (row.order_items ?? []).map((line) => ({
    key: `${line.product_id ?? line.id}::${line.size || "regular"}`,
    id: line.product_id,
    name: line.name,
    image: line.image,
    size: line.size || null,
    price: Number(line.unit_price),
    qty: line.qty,
  }));

  return {
    id: row.id,
    reference: row.reference,
    status: row.status,
    // `method` on screen means how the customer paid; delivery/pickup lives in
    // `methodLabel`, exactly as the original frontend named them.
    method: row.payment_method ?? "—",
    methodLabel: row.method === "pickup" ? "Pickup" : "Delivery",
    deliveryMethod: row.method,
    paymentMethod: row.payment_method ?? null,
    placedAt: row.placed_at,
    subtotal: Number(row.subtotal ?? 0),
    discount: Number(row.discount ?? 0),
    shipping: Number(row.shipping ?? 0),
    total: Number(row.total ?? 0),
    promoCode: row.promo_code ?? null,
    address: row.address ?? null,
    contact: row.contact ?? null,
    customer: row.customer_name ?? "Guest",
    itemCount: Number(row.item_count ?? items.reduce((n, i) => n + i.qty, 0)),
    items,
  };
}

export const orderService = {
  /* ---------------- Checkout draft (transient, session-scoped) -------------- */

  getDraft: read,
  saveDraft: write,

  clearDraft() {
    try {
      window.sessionStorage.removeItem(DRAFT_KEY);
    } catch {
      /* no-op */
    }
  },

  /** Placeholder shown while checkout is in progress; the real reference is
   *  generated by the database when the order is placed. */
  createReference() {
    return `KAP-${Math.floor(1000 + Math.random() * 9000)}`;
  },

  /* ------------------------------- Orders ---------------------------------- */

  /**
   * Places the order server-side and returns the stored order (with items).
   * Throws with a human-readable message on failure — nothing is written.
   */
  async placeOrder({ method = "delivery", paymentMethod, address, contact, promoCode } = {}) {
    const supabase = getSupabase();
    const { data, error } = await supabase.rpc("place_order", {
      p_method: method === "pickup" ? "pickup" : "delivery",
      p_payment_method: paymentMethod ?? null,
      p_address: address ?? null,
      p_contact: contact ?? null,
      p_promo_code: promoCode ?? null,
    });
    if (error) throw new Error(error.message || "We couldn’t place your order. Please try again.");
    if (!data?.reference) throw new Error("We couldn’t place your order. Please try again.");

    return orderService.getOrder(data.reference);
  },

  /** Every order for the signed-in customer, newest first. */
  async getOrders() {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from("orders")
      .select(ORDER_SELECT)
      .order("placed_at", { ascending: false });
    if (error) throw new Error(error.message);
    return (data ?? []).map(rowToOrder);
  },

  /** Single order by its human-friendly reference (`KAP-4821`). */
  async getOrder(reference) {
    if (!reference) return null;
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from("orders")
      .select(ORDER_SELECT)
      .eq("reference", String(reference).toUpperCase())
      .maybeSingle();
    if (error) throw new Error(error.message);
    return rowToOrder(data);
  },

  /** Append-only status timeline for the order detail / tracking views. */
  async getStatusEvents(orderId) {
    if (!orderId) return [];
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from("order_status_events")
      .select("status,note,created_at")
      .eq("order_id", orderId)
      .order("created_at", { ascending: true });
    if (error) throw new Error(error.message);
    return data ?? [];
  },
};

export default orderService;
